### ISSUE TITLE
Python 3.10 not supported

### ISSUE THREAD

**Issue by johnnymccloud** [TexZK/hexrec#13]
When I try to import the hexrec.records using newest python it says there is no module:
  import hexrec.records as hr
  ModuleNotFoundError: No module named 'hexrec.records'

It is installed though, and worked in python 3.9.

**Comment by TexZK** [comment]
It looks like the PIP installation falls back to the very outdated `hexrec-0.0.1` because of installation issues.

For some reason, the `pathlib` package is still willing to import `Sequence` from `collections` instead of `collections.abc`.
This is deprecared since Python 3.3, and not working anymore since Pyhton 3.10.

Here's some output when I tried to install the `hexrec` package into a clean Python 3.10 installation from source:
```sh
texzk@vbox:~/venv$ python3.10 -m venv py310
texzk@vbox:~/venv$ source py310/bin/activate
(py310) texzk@vbox:~/venv$ python --version
Python 3.10.0
(py310) texzk@vbox:~/venv$ python -m pip install hexrec
Collecting hexrec
  Downloading hexrec-0.2.2-py2.py3-none-any.whl (73 kB)
     |████████████████████████████████| 73 kB 795 kB/s 
Collecting pathlib
  Downloading pathlib-1.0.1.tar.gz (49 kB)
     |████████████████████████████████| 49 kB 159 kB/s 
    ERROR: Command errored out with exit status 1:
     command: /home/texzk/venv/py310/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-eso1am07/pathlib_274723f5058c46278adb72e6d6e82b4c/setup.py'"'"'; __file__='"'"'/tmp/pip-install-eso1am07/pathlib_274723f5058c46278adb72e6d6e82b4c/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-pu6jn866                                                                                                                                                                                                                   
         cwd: /tmp/pip-install-eso1am07/pathlib_274723f5058c46278adb72e6d6e82b4c/                                                                                                                                                                                             
    Complete output (13 lines):                                                                                                                                                                                                                                               
    Traceback (most recent call last):                                                                                                                                                                                                                                        
      File "<string>", line 1, in <module>                                                                                                                                                                                                                                    
      File "/home/texzk/venv/py310/lib/python3.10/site-packages/setuptools/__init__.py", line 16, in <module>                                                                                                                                                                 
        import setuptools.version                                                                                                                                                                                                                                             
      File "/home/texzk/venv/py310/lib/python3.10/site-packages/setuptools/version.py", line 1, in <module>                                                                                                                                                                   
        import pkg_resources                                                                                                                                                                                                                                                  
      File "/home/texzk/venv/py310/lib/python3.10/site-packages/pkg_resources/__init__.py", line 23, in <module>                                                                                                                                                              
        import zipfile                                                                                                                                                                                                                                                        
      File "/usr/local/lib/python3.10/zipfile.py", line 19, in <module>                                                                                                                                                                                                       
        import pathlib                                                                                                                                                                                                                                                        
      File "/tmp/pip-install-eso1am07/pathlib_274723f5058c46278adb72e6d6e82b4c/pathlib.py", line 10, in <module>                                                                                                                                                              
        from collections import Sequence                                                                                                                                                                                                                                      
    ImportError: cannot import name 'Sequence' from 'collections' (/usr/local/lib/python3.10/collections/__init__.py)                                                                                                                                                         
    ----------------------------------------                                                                                                                                                                                                                                  
WARNING: Discarding https://files.pythonhosted.org/packages/ac/aa/9b065a76b9af472437a0059f77e8f962fe350438b927cb80184c32f075eb/pathlib-1.0.1.tar.gz#sha256=6940718dfc3eff4258203ad5021090933e5c04707d5ca8cc9e73c94a7894ea9f (from https://pypi.org/simple/pathlib/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
Then PIP tries to downgrade each previous version of `hexrec` and `pathlib`, until `hexrec-0.0.1` gives no more errors.

**Comment by TexZK** [comment]
The very same thing happens with Anaconda 3.
It really looks there's something broken when installing the `pathlib` package itself.

```bat
(base) C:\Users\texzk>conda create -n py310 python=3.10
    [...]
(base) C:\Users\texzk>conda activate py310
(py310) C:\Users\texzk>pip install pathlib
Collecting pathlib
  Using cached pathlib-1.0.1.tar.gz (49 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Anaconda3\envs\py310\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\texzk\\AppData\\Local\\Temp\\pip-install-xj3xmej6\\pathlib_73a813d0a1444085ab21ee23dd3c793a\\setup.py'"'"'; __file__='"'"'C:\\Users\\texzk\\AppData\\Local\\Temp\\pip-install-xj3xmej6\\pathlib_73a813d0a1444085ab21ee23dd3c793a\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\texzk\AppData\Local\Temp\pip-pip-egg-info-4mhwnafo'
         cwd: C:\Users\texzk\AppData\Local\Temp\pip-install-xj3xmej6\pathlib_73a813d0a1444085ab21ee23dd3c793a\
    Complete output (13 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Anaconda3\envs\py310\lib\site-packages\setuptools\__init__.py", line 16, in <module>
        import setuptools.version
      File "C:\Anaconda3\envs\py310\lib\site-packages\setuptools\version.py", line 1, in <module>
        import pkg_resources
      File "C:\Anaconda3\envs\py310\lib\site-packages\pkg_resources\__init__.py", line 23, in <module>
        import zipfile
      File "C:\Anaconda3\envs\py310\lib\zipfile.py", line 19, in <module>
        import pathlib
      File "C:\Users\texzk\AppData\Local\Temp\pip-install-xj3xmej6\pathlib_73a813d0a1444085ab21ee23dd3c793a\pathlib.py", line 10, in <module>
        from collections import Sequence
    ImportError: cannot import name 'Sequence' from 'collections' (C:\Anaconda3\envs\py310\lib\collections\__init__.py)
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/ac/aa/9b065a76b9af472437a0059f77e8f962fe350438b927cb80184c32f075eb/pathlib-1.0.1.tar.gz#sha256=6940718dfc3eff4258203ad5021090933e5c04707d5ca8cc9e73c94a7894ea9f (from https://pypi.org/simple/pathlib/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    [...]
ERROR: Could not find a version that satisfies the requirement pathlib (from versions: 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.97, 1.0, 1.0.1)
ERROR: No matching distribution found for pathlib
```

**Comment by TexZK** [comment]
Well, it's easier done than said: just remove pathlib from the requirements of setup.py, and it should work.
I committed this very small change, so you can install from source until I release a new version (hopefully soon).
